pheature_flags:
  driver: inmemory
  toggles:
    # RELEASE TOGGLES
    - { id: show_brand_logo, enabled: true }
    - { id: show_commercial_name, enabled: true }
    - { id: show_home_dynamic_catalog, enabled: false }
    - { id: show_contact_info, enabled: true }
    -
      id: admin_dashboard
      enabled: true
      strategies:
        -
          strategy_id: 'enable_for_developers'
          strategy_type: 'enable_by_matching_segment'
          segments:
            -
              segment_id: 'is_developer'
              segment_type: 'strict_matching_segment'
              criteria:
                - 'developer'
