pheature_flags:
  driver: inmemory
  toggles:
    # RELEASE TOGGLES
    - { id: show_brand_logo, enabled: true }
    - { id: show_commercial_name, enabled: true }
    - { id: show_home_pictures, enabled: true }
