#index:
#    path: /
#    controller: App\Controller\DefaultController::index
logout:
  path: /logout

pheature_flags:
  resource: '@PheatureFlagsBundle/Resources/config/toggle_api/routes.yaml'
  prefix: '%pheature_flags_prefix%'
